version: '3.8'
services:
    savesclient:
        build: ./front
        env_file: 
        - ./.env
        ports:
        - "8080:8080"
        links:
        - savesweb
    savesweb:
        build: ./back
        env_file: 
        - ./.env
        ports:
        - "8000:8000"
        volumes:
        - .:/opt
        links:
        - savesmongo
    savesmongo:
        image: mongo
        env_file: 
            - ./.env
        ports:
            - "27017:27017"
        volumes:
        - mongo-data:/data/db
        - mongo-configdb:/data/configdb
volumes:
    mongo-data:
    mongo-configdb: